version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017

  server:
    build: server
    image: rovr/server
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - mongodb
    links:
      - mongodb
    
  web:
    build: web
    image: rovr/web
    restart: always
    ports:
      - 8002:80
    depends_on:
      - server
    links:
      - server

  dashboard:
    build: dashboard
    image: rovr/dashboard
    restart: always
    ports:
      - 8003:80
    depends_on:
      - server
    links:
      - server

